/* 오늘 딱 한 문장 — 1개월차 30문장
   「나를 설명하는 영어」 · Day 1부터 순서대로 이어집니다.

   S(day, 영어, 직역, 이런느낌, 발음, 쪼개기, 이런순간에, 예시대화, 비슷한표현)
     예시대화 · 비슷한표현 = [영어, 뜻, 한글발음] 세 개씩 */

const S = (day, en, ko, ko2, rd, bd, when, ex, sim) =>
  ({ id: 'd' + day, day, en, ko, ko2, rd, bd, when, ex, sim });

const SENTENCES = [

/* ── 1~7 영어 공부 이야기 ── */
S(1, "I'm learning English.", "영어 배우고 있어요.",
  "잘한다는 말이 아니라 「지금 배우는 중」이라는 말이에요. 부담이 확 줄어요.",
  "아임 러닝 잉글리시",
  [["I'm","나는 ~예요 (I am 을 줄인 말)"],["learning English","영어를 배우고 있는"]],
  '첫 문장이에요. 이 말을 먼저 하면 상대가 속도를 줄이고 쉬운 말로 바꿔줘요.',
  [["A: Do you speak English?","영어 하세요?","두유 스픽 잉글리시?"],
   ["B: A little. I'm learning English.","조금요. 배우는 중이에요.","어 리틀. 아임 러닝 잉글리시"]],
  [["I'm studying English.","영어 공부하고 있어요.","아임 스터딩 잉글리시"],
   ["I'm trying to learn English.","영어 배워보려고 해요.","아임 트라잉 투 런 잉글리시"]]),

S(2, "I'm a complete beginner.", "저 완전 초보예요.",
  "부끄러운 말이 아니라 「편하게 해주세요」라는 신호예요.",
  "아임 어 컴플릿 비기너",
  [["a complete","완전한"],["beginner","초보자"]],
  'complete 가 "완전한"이에요. 이 말을 하면 상대가 알아서 쉬운 단어를 골라줘요.',
  [["A: How's your English?","영어 어느 정도 하세요?","하우즈 유어 잉글리시?"],
   ["B: I'm a complete beginner.","저 완전 초보예요.","아임 어 컴플릿 비기너"]],
  [["I'm just starting out.","이제 막 시작했어요.","아임 저스트 스타팅 아웃"],
   ["I'm very new to this.","이건 아주 처음이에요.","아임 베리 뉴 투 디스"]]),

S(3, "I'm taking it slow.", "천천히 하고 있어요.",
  "「조급해하지 않는다」는 뜻이에요. 공부·일·운동 어디에나 그대로 써요.",
  "아임 테이킹 잇 슬로우",
  [["I'm","나는 ~예요"],["taking it slow","서두르지 않고 천천히 하는"]],
  '남이 재촉할 때 쓰면 딱 좋아요.',
  [["A: Are you in a rush to improve?","빨리 늘고 싶으세요?","아유 인 어 러시 투 임프루브?"],
   ["B: No, I'm taking it slow.","아뇨, 천천히 하고 있어요.","노, 아임 테이킹 잇 슬로우"]],
  [["I'm in no rush.","급할 거 없어요.","아임 인 노 러시"],
   ["One step at a time.","한 번에 하나씩요.","원 스텝 앳 어 타임"]]),

S(4, "I like learning new things.", "새로운 거 배우는 걸 좋아해요.",
  "나를 한마디로 소개할 때 쓰는 문장이에요.",
  "아이 라익 러닝 뉴 띵스",
  [["I like","나는 좋아해요"],["learning new things","새로운 걸 배우는 것을"]],
  'I like 뒤에는 -ing 를 붙여요. like to learn 도 맞지만 말할 땐 learning 이 더 흔해요.',
  [["A: Why did you start?","왜 시작하셨어요?","와이 디쥬 스타트?"],
   ["B: I like learning new things.","새로운 거 배우는 걸 좋아해서요.","아이 라익 러닝 뉴 띵스"]],
  [["I enjoy learning.","배우는 게 즐거워요.","아이 인조이 러닝"],
   ["I'm curious about a lot of things.","궁금한 게 많아요.","아임 큐리어스 어바웃 어 랏 오브 띵스"]]),

S(5, "I try to do a little every day.", "매일 조금씩 하려고 해요.",
  "「많이는 못 해도 꾸준히」라는 뜻이에요. 완벽하지 않아도 되는 말이에요.",
  "아이 트라이 투 두 어 리틀 에브리데이",
  [["I try to","~하려고 해요"],["do a little","조금 하다"],["every day","매일"]],
  'I try to 가 "하려고 노력한다"예요. 못 지킨 날이 있어도 거짓말이 안 돼요.',
  [["A: How often do you study?","얼마나 자주 하세요?","하우 오픈 두유 스터디?"],
   ["B: I try to do a little every day.","매일 조금씩 하려고 해요.","아이 트라이 투 두 어 리틀 에브리데이"]],
  [["I do a bit each day.","하루에 조금씩 해요.","아이 두 어 빗 이치 데이"],
   ["Just a few minutes a day.","하루 몇 분만요.","저스트 어 퓨 미닛츠 어 데이"]]),

S(6, "I don't always feel like it.", "항상 하고 싶은 건 아니에요.",
  "「솔직히 하기 싫은 날도 있어요」라는 말이에요.",
  "아이 돈 올웨이즈 필 라이킷",
  [["don't always","항상 ~하는 건 아니다"],["feel like it","그걸 하고 싶다"]],
  'feel like it 이 "그게 내키다"예요. 아주 많이 쓰는 덩어리라 통째로 외워두세요.',
  [["A: Do you enjoy it every day?","매일 즐거우세요?","두유 인조이 잇 에브리데이?"],
   ["B: Honestly, I don't always feel like it.","솔직히, 항상 그렇진 않아요.","아너스틀리, 아이 돈 올웨이즈 필 라이킷"]],
  [["Some days I don't want to.","어떤 날은 하기 싫어요.","썸 데이즈 아이 돈 원트 투"],
   ["It's not always fun.","늘 재밌진 않아요.","잇츠 낫 올웨이즈 펀"]]),

S(7, "But I still try.", "그래도 해보려고 해요.",
  "6번 바로 뒤에 붙이는 문장이에요. 둘을 이어 말하면 그대로 한 이야기가 돼요.",
  "벗 아이 스틸 트라이",
  [["But","그래도"],["I still try","나는 여전히 해봐요"]],
  '짧지만 힘이 있는 문장이에요. 「그래도 한다」가 이 앱의 전부이기도 하고요.',
  [["A: Even on bad days?","힘든 날에도요?","이븐 온 배드 데이즈?"],
   ["B: But I still try.","그래도 해보려고 해요.","벗 아이 스틸 트라이"]],
  [["I show up anyway.","그래도 일단 해요.","아이 쇼 업 애니웨이"],
   ["I keep at it.","계속 붙잡고 있어요.","아이 킵 앳 잇"]]),

/* ── 8~15 요즘 만드는 것 ── */
S(8, "I'm learning to code.", "코딩을 배우고 있어요.",
  "「프로그래밍 공부 중이에요」라는 말이에요.",
  "아임 러닝 투 코드",
  [["learning to","~하는 법을 배우는 중"],["code","코딩하다"]],
  'learn 뒤에 "~하는 법"을 넣을 땐 to 를 써요. learning English 와 모양이 다른 이유예요.',
  [["A: What else are you up to?","또 뭐 하고 지내세요?","왓 엘스 아유 업 투?"],
   ["B: I'm learning to code.","코딩 배우고 있어요.","아임 러닝 투 코드"]],
  [["I'm teaching myself to code.","혼자 코딩 공부해요.","아임 티칭 마이셀프 투 코드"],
   ["I'm picking up programming.","프로그래밍 익히는 중이에요.","아임 피킹 업 프로그래밍"]]),

S(9, "I'm working on a small project.", "작은 프로젝트 하나 만들고 있어요.",
  "「뭔가 하나 만들고 있어요」. 거창하지 않게 말하는 방법이에요.",
  "아임 워킹 온 어 스몰 프로젝트",
  [["working on","~를 작업 중인"],["a small project","작은 프로젝트 하나"]],
  'work on 이 "~를 만들고 있다"예요. 일·그림·글 전부 이 표현을 써요.',
  [["A: Anything fun lately?","요즘 재밌는 거 있어요?","애니띵 펀 레잇리?"],
   ["B: I'm working on a small project.","작은 거 하나 만들고 있어요.","아임 워킹 온 어 스몰 프로젝트"]],
  [["I've got a side project.","따로 하는 게 하나 있어요.","아이브 갓 어 사이드 프로젝트"],
   ["I'm building something small.","작은 거 만들고 있어요.","아임 빌딩 썸띵 스몰"]]),

S(10, "I use Claude Code almost every day.", "Claude Code를 거의 매일 써요.",
  "almost 를 넣으면 「매일은 아니지만 거의」가 돼요. 과장이 안 돼요.",
  "아이 유즈 클로드 코드 올모스트 에브리데이",
  [["I use","써요"],["almost","거의"],["every day","매일"]],
  '쓰는 도구를 말할 때예요. Claude Code 자리에 다른 걸 넣어도 그대로 써요.',
  [["A: What tools do you use?","어떤 걸 쓰세요?","왓 툴즈 두유 유즈?"],
   ["B: I use Claude Code almost every day.","Claude Code를 거의 매일 써요.","아이 유즈 클로드 코드 올모스트 에브리데이"]],
  [["I'm on it most days.","거의 매일 붙어 있어요.","아임 온 잇 모스트 데이즈"],
   ["I use it a lot.","많이 써요.","아이 유즈 잇 어 랏"]]),

S(11, "I worked on it again today.", "오늘도 그거 작업했어요.",
  "「오늘도 했다」는 말이에요. 9번의 과거형이에요.",
  "아이 웍트 온 잇 어겐 투데이",
  [["worked on it","그걸 작업했다"],["again today","오늘도 또"]],
  '⚠️ worked 의 ed 는 "드"가 아니라 "트"로 짧게 소리 나요. "웍트".',
  [["A: Did you take a break?","좀 쉬셨어요?","디쥬 테익 어 브레이크?"],
   ["B: No, I worked on it again today.","아뇨, 오늘도 했어요.","노, 아이 웍트 온 잇 어겐 투데이"]],
  [["I put some time in today.","오늘도 시간 좀 들였어요.","아이 풋 썸 타임 인 투데이"],
   ["I kept going today.","오늘도 이어서 했어요.","아이 켑트 고잉 투데이"]]),

S(12, "I got a little done.", "조금 해냈어요.",
  "「많이는 못 했지만 뭔가는 했어요」. 자책 대신 쓰는 말이에요.",
  "아이 갓 어 리틀 던",
  [["I","나는"],["got a little done","조금 해냈어요"]],
  '적게 했어도 「해냈다」고 말할 수 있어요. 기분이 달라지는 문장이에요.',
  [["A: How did it go?","어떻게 됐어요?","하우 디딧 고?"],
   ["B: I got a little done.","조금 해냈어요.","아이 갓 어 리틀 던"]],
  [["I made some progress.","좀 나아갔어요.","아이 메이드 썸 프로그레스"],
   ["Not much, but something.","많진 않아도 뭔가는요.","낫 머치, 벗 썸띵"]]),

S(13, "I'm still figuring it out.", "아직 하나씩 알아가는 중이에요.",
  "「아직 잘 모르겠어요」를 당당하게 말하는 방법이에요.",
  "아임 스틸 피겨링 잇 아웃",
  [["still","아직"],["figuring it out","그걸 알아내는 중"]],
  '원어민이 매일 쓰는 말이에요. 모른다고 해도 전혀 부끄럽지 않게 들려요.',
  [["A: Do you know how it works?","이거 어떻게 되는지 아세요?","두유 노 하우 잇 웍스?"],
   ["B: I'm still figuring it out.","아직 알아가는 중이에요.","아임 스틸 피겨링 잇 아웃"]],
  [["I'm getting there.","점점 되고 있어요.","아임 게팅 데어"],
   ["I haven't got it yet.","아직 감이 안 와요.","아이 해븐 갓 잇 옛"]]),

S(14, "I learn from my mistakes.", "실수하면서 배워요.",
  "실수 얘기가 나왔을 때 분위기를 가볍게 만드는 말이에요.",
  "아이 런 프롬 마이 미스테익스",
  [["learn from","~로부터 배우다"],["my mistakes","내 실수들"]],
  '변명이 아니라 태도를 말하는 문장이에요.',
  [["A: You broke it again!","또 망가뜨렸네요!","유 브로크 잇 어겐!"],
   ["B: I learn from my mistakes.","실수하면서 배우는 거죠.","아이 런 프롬 마이 미스테익스"]],
  [["Mistakes help me learn.","실수가 도움이 돼요.","미스테익스 헬프 미 런"],
   ["That's how I learn.","그렇게 배우는 거죠.","댓츠 하우 아이 런"]]),

S(15, "I like making things.", "뭔가 만드는 걸 좋아해요.",
  "앱이든 뜨개질이든 다 들어가요. 나를 한마디로 설명하는 문장이에요.",
  "아이 라익 메이킹 띵스",
  [["like making","만드는 걸 좋아하다"],["things","것들을"]],
  '취미를 길게 설명하지 않고 한 번에 말하는 방법이에요.',
  [["A: What do you enjoy?","뭘 좋아하세요?","왓 두유 인조이?"],
   ["B: I like making things.","뭔가 만드는 걸 좋아해요.","아이 라익 메이킹 띵스"]],
  [["I'm a maker.","만드는 사람이에요.","아임 어 메이커"],
   ["I like building stuff.","뭔가 짓는 걸 좋아해요.","아이 라익 빌딩 스터프"]]),

/* ── 16~20 일상과 취향 ── */
S(16, "I like having a simple routine.", "단순한 루틴을 좋아해요.",
  "「매일 똑같은 흐름이 편해요」라는 뜻이에요.",
  "아이 라익 해빙 어 심플 루틴",
  [["like having","가지는 걸 좋아하다"],["a simple routine","단순한 하루 틀"]],
  'routine 은 "매일 같은 흐름"이에요. 복수 routines 보다 a simple routine 이 말할 때 자연스러워요.',
  [["A: Do you plan your days?","하루 계획 세우세요?","두유 플랜 유어 데이즈?"],
   ["B: I like having a simple routine.","단순한 루틴이 좋아요.","아이 라익 해빙 어 심플 루틴"]],
  [["I keep my days simple.","하루를 단순하게 둬요.","아이 킵 마이 데이즈 심플"],
   ["I like a steady rhythm.","일정한 리듬이 좋아요.","아이 라익 어 스테디 리듬"]]),

S(17, "I spend a lot of time at home.", "집에서 시간을 많이 보내요.",
  "「집순이예요」를 돌려 말하는 방법이에요.",
  "아이 스펜드 어 랏 오브 타임 앳 홈",
  [["spend a lot of time","시간을 많이 보내다"],["at home","집에서"]],
  'spend 는 돈에도 시간에도 써요. 집에 있는 걸 편하게 말할 수 있어요.',
  [["A: Do you go out much?","밖에 자주 나가세요?","두유 고 아웃 머치?"],
   ["B: Not really. I spend a lot of time at home.","별로요. 집에 많이 있어요.","낫 륄리. 아이 스펜드 어 랏 오브 타임 앳 홈"]],
  [["I'm a homebody.","집순이예요.","아임 어 홈바디"],
   ["I'm usually in.","보통 집에 있어요.","아임 유주얼리 인"]]),

S(18, "I play games in my free time.", "시간 날 때 게임해요.",
  "취미를 말하는 틀이에요. 앞부분만 바꾸면 다 돼요.",
  "아이 플레이 게임스 인 마이 프리 타임",
  [["play games","게임을 하다"],["in my free time","여유 시간에"]],
  'in my free time 은 통째로 외워두면 어떤 취미에도 붙여 쓸 수 있어요.',
  [["A: What do you do to relax?","쉴 때 뭐 하세요?","왓 두유 두 투 릴랙스?"],
   ["B: I play games in my free time.","시간 날 때 게임해요.","아이 플레이 게임스 인 마이 프리 타임"]],
  [["I game a bit.","게임 좀 해요.","아이 게임 어 빗"],
   ["Gaming, mostly.","주로 게임이요.","게이밍, 모스틀리"]]),

S(19, "I also like knitting.", "뜨개질도 좋아해요.",
  "앞말에 하나 더 얹을 때 쓰는 also 예요.",
  "아이 올소 라익 니팅",
  [["also","~도"],["knitting","뜨개질"]],
  '⚠️ knitting 의 k 는 소리가 안 나요. "니팅"이에요. know, knee 도 똑같아요.',
  [["A: Only games?","게임만요?","온리 게임스?"],
   ["B: I also like knitting.","뜨개질도 좋아해요.","아이 올소 라익 니팅"]],
  [["Knitting, too.","뜨개질도요.","니팅, 투"],
   ["I knit as well.","뜨개질도 해요.","아이 닛 애즈 웰"]]),

S(20, "I like having time to myself.", "혼자만의 시간이 있는 걸 좋아해요.",
  "「외롭다」가 아니라 「혼자가 편하다」는 뜻이에요.",
  "아이 라익 해빙 타임 투 마이셀프",
  [["time to myself","나만의 시간"]],
  '영어에서 아주 자주 쓰는 표현이에요. 거절할 때도 부드럽게 쓸 수 있어요.',
  [["A: Want to join us?","같이 가실래요?","원투 조인 어스?"],
   ["B: Maybe next time. I like having time to myself.","다음에요. 혼자 있는 시간이 좋아서요.","메이비 넥스트 타임. 아이 라익 해빙 타임 투 마이셀프"]],
  [["I need my own space.","제 공간이 필요해요.","아이 니드 마이 오운 스페이스"],
   ["I recharge alone.","혼자 있어야 충전돼요.","아이 리차지 얼론"]]),

/* ── 21~27 성격 · 감정 · 습관 ── */
S(21, "I get nervous about the future sometimes.", "가끔 미래 생각하면 불안해져요.",
  "「늘 그런 건 아닌데 가끔 그래요」라는 뜻이에요.",
  "아이 겟 너버스 어바웃 더 퓨처 썸타임즈",
  [["get nervous","불안해지다"],["about the future","미래에 대해"],["sometimes","가끔"]],
  'get 은 "~해지다"예요. I am nervous 는 지금 상태, I get nervous 는 "그럴 때가 있다"예요.',
  [["A: You seem quiet.","조용하시네요.","유 씸 콰이엇"],
   ["B: I get nervous about the future sometimes.","가끔 앞날이 불안해져요.","아이 겟 너버스 어바웃 더 퓨처 썸타임즈"]],
  [["The future worries me a bit.","앞날이 좀 걱정돼요.","더 퓨처 워리즈 미 어 빗"],
   ["I think about it a lot.","생각이 많아요.","아이 띵크 어바웃 잇 어 랏"]]),

S(22, "I worry about money sometimes.", "가끔 돈 걱정을 해요.",
  "무겁지 않게 솔직한 얘기를 꺼내는 방법이에요.",
  "아이 워리 어바웃 머니 썸타임즈",
  [["worry about","~를 걱정하다"],["money","돈"]],
  'sometimes 를 끝에 붙이면 처지지 않고 담담하게 들려요.',
  [["A: What's on your mind?","무슨 생각 하세요?","왓츠 온 유어 마인드?"],
   ["B: I worry about money sometimes.","가끔 돈 걱정을 해요.","아이 워리 어바웃 머니 썸타임즈"]],
  [["Money's on my mind.","돈 생각이 나요.","머니즈 온 마이 마인드"],
   ["It's a bit tight these days.","요즘 좀 빠듯해요.","잇츠 어 빗 타잇 디즈 데이즈"]]),

S(23, "I get overwhelmed sometimes.", "가끔 벅찰 때가 있어요.",
  "한국어 「벅차다」와 거의 똑같은 느낌이에요.",
  "아이 겟 오버웰름드 썸타임즈",
  [["get overwhelmed","벅차지다"]],
  'overwhelmed 는 "감당이 안 될 만큼 밀려온" 느낌이에요.',
  [["A: Too much going on?","일이 너무 많아요?","투 머치 고잉 온?"],
   ["B: Yeah, I get overwhelmed sometimes.","네, 가끔 벅차요.","예, 아이 겟 오버웰름드 썸타임즈"]],
  [["It piles up sometimes.","가끔 쌓여요.","잇 파일즈 업 썸타임즈"],
   ["It's a lot some days.","어떤 날은 많아요.","잇츠 어 랏 썸 데이즈"]]),

S(24, "So I take things one step at a time.", "그래서 하나씩 하려고 해요.",
  "23번 뒤에 붙이면 「벅차지만 하나씩 한다」는 이야기가 완성돼요.",
  "쏘 아이 테익 띵스 원 스텝 앳 어 타임",
  [["So","그래서"],["take things one step at a time","하나씩 차근차근 해요"]],
  '굳어진 관용구라 통째로 외우는 게 맞아요. 아주 자주 들려요.',
  [["A: How do you handle it?","어떻게 버티세요?","하우 두유 핸들 잇?"],
   ["B: So I take things one step at a time.","그래서 하나씩 해요.","쏘 아이 테익 띵스 원 스텝 앳 어 타임"]],
  [["Little by little.","조금씩요.","리틀 바이 리틀"],
   ["One thing at a time.","한 번에 하나씩요.","원 띵 앳 어 타임"]]),

S(25, "It takes me a while to get started.", "저는 시작하는 데 시간이 좀 걸려요.",
  "「엉덩이가 무거워요」를 영어로 말하면 이렇게 돼요.",
  "잇 테익스 미 어 와일 투 겟 스타티드",
  [["It takes me","나에게 ~가 걸린다"],["a while","한참"],["get started","시작하다"]],
  'It takes me ~ 는 "나는 ~가 걸린다"는 틀이에요. 뒤만 바꾸면 그대로 써요.',
  [["A: You're slow to begin.","시작이 느리시네요.","유어 슬로우 투 비긴"],
   ["B: It takes me a while to get started.","시작하는 데 시간이 걸려요.","잇 테익스 미 어 와일 투 겟 스타티드"]],
  [["I'm a slow starter.","시작이 느린 편이에요.","아임 어 슬로우 스타터"],
   ["Getting going is the hard part.","시작이 제일 어려워요.","게팅 고잉 이즈 더 하드 파트"]]),

S(26, "But once I start, I can focus pretty well.", "그래도 시작하면 꽤 집중하는 편이에요.",
  "25번 뒤에 붙이는 반전이에요. 「느리지만 집중은 잘한다」",
  "벗 원스 아이 스타트, 아이 캔 포커스 프리티 웰",
  [["once I start","일단 시작하면"],["focus","집중하다"],["pretty well","꽤 잘"]],
  '⚠️ pretty 는 "예쁜"이 아니라 "꽤"로 쓰여요. 자랑처럼 안 들리게 해주는 단어예요.',
  [["A: Really?","정말요?","륄리?"],
   ["B: But once I start, I can focus pretty well.","시작만 하면 꽤 집중해요.","벗 원스 아이 스타트, 아이 캔 포커스 프리티 웰"]],
  [["I get into it eventually.","결국엔 빠져들어요.","아이 겟 인투 잇 이벤추얼리"],
   ["Once I'm in, I'm in.","한번 들어가면 쭉 가요.","원스 아임 인, 아임 인"]]),

S(27, "I'm trying to be more consistent.", "좀 더 꾸준해지려고 하고 있어요.",
  "지금 이 앱을 쓰는 이유 그 자체인 문장이에요.",
  "아임 트라잉 투 비 모어 컨시스턴트",
  [["trying to be","~가 되려고 노력 중인"],["more consistent","더 꾸준한"]],
  'consistent 가 "꾸준한"이에요. 목표를 말할 때 아주 많이 써요.',
  [["A: Any goals this year?","올해 목표 있어요?","애니 골즈 디스 이어?"],
   ["B: I'm trying to be more consistent.","좀 더 꾸준해지려고요.","아임 트라잉 투 비 모어 컨시스턴트"]],
  [["I want to keep it steady.","꾸준히 가고 싶어요.","아이 원트 투 킵 잇 스테디"],
   ["Showing up is the goal.","빠지지 않는 게 목표예요.","쇼잉 업 이즈 더 골"]]),

/* ── 28~30 원하는 삶 ── */
S(28, "I just want a stable life.", "그냥 안정적인 삶을 원해요.",
  "just 하나로 선언이 아니라 속마음처럼 들려요.",
  "아이 저스트 원트 어 스테이블 라이프",
  [["just","그냥"],["want","원하다"],["a stable life","안정적인 삶"]],
  '큰 꿈을 말해야 할 것 같을 때, 담담하게 대답하는 문장이에요.',
  [["A: What's your dream?","꿈이 뭐예요?","왓츠 유어 드림?"],
   ["B: Nothing big. I just want a stable life.","거창한 건 없어요. 그냥 안정적이면 돼요.","낫띵 빅. 아이 저스트 원트 어 스테이블 라이프"]],
  [["I'm after something steady.","안정적인 걸 바라요.","아임 애프터 썸띵 스테디"],
   ["Simple and steady is enough.","단순하고 안정적이면 충분해요.","심플 앤 스테디 이즈 이너프"]]),

S(29, "I want to keep learning.", "계속 배우고 싶어요.",
  "「여기서 멈추고 싶지 않아요」라는 뜻이에요.",
  "아이 원트 투 킵 러닝",
  [["want to","~하고 싶다"],["keep learning","계속 배우다"]],
  'keep 뒤에는 -ing 를 써요. keep going, keep trying 도 똑같은 모양이에요.',
  [["A: And after that?","그다음엔요?","앤 애프터 댓?"],
   ["B: I want to keep learning.","계속 배우고 싶어요.","아이 원트 투 킵 러닝"]],
  [["I'm not done learning.","아직 다 안 배웠어요.","아임 낫 던 러닝"],
   ["There's always more.","늘 더 있잖아요.","데얼즈 올웨이즈 모어"]]),

S(30, "I'm glad I kept going.", "계속 해온 게 기뻐요.",
  "30일째 문장이에요. 이 말은 한 달을 채운 사람만 할 수 있어요.",
  "아임 글래드 아이 켑트 고잉",
  [["I'm glad","기뻐요"],["I kept going","계속 해왔다"]],
  'kept 는 keep 의 과거형이에요. 포기하지 않았다는 뜻이 담겨요.',
  [["A: You stuck with it.","끝까지 하셨네요.","유 스턱 윗 잇"],
   ["B: I'm glad I kept going.","계속 해온 게 기뻐요.","아임 글래드 아이 켑트 고잉"]],
  [["It was worth it.","할 만했어요.","잇 워즈 워쓰 잇"],
   ["I'm glad I didn't quit.","안 그만두길 잘했어요.","아임 글래드 아이 디든 큇"]]),

];

/* 내 문장으로 바꿔보기 — 틀을 바꿔 쓰기 쉬운 문장에만 답니다.
   없는 날은 이 칸 자체가 안 보입니다. 기존 30문장은 건드리지 않습니다.
   { before:앞부분, after:뒷부분, opts:[[영어, 뜻], ...] }  열쇠는 DAY 번호 */
const PATTERNS = {
  1:  { before:"I'm learning ", after:".",
        opts:[["Korean","한국어"],["to cook","요리하는 법"],["to swim","수영하는 법"],["to draw","그림 그리는 법"]] },
  8:  { before:"I'm learning to ", after:".",
        opts:[["swim","수영하다"],["knit","뜨개질하다"],["cook","요리하다"],["drive","운전하다"]] },
  15: { before:"I like making ", after:".",
        opts:[["things","물건"],["food","음식"],["videos","영상"],["clothes","옷"]] },
  17: { before:"I spend a lot of time ", after:".",
        opts:[["at home","집에서"],["outside","밖에서"],["with my family","가족이랑"],["on my phone","휴대폰 보면서"]] },
  18: { before:"I ", after:" in my free time.",
        opts:[["play games","게임해요"],["read books","책 읽어요"],["knit","뜨개질해요"],["take walks","산책해요"]] },
  22: { before:"I worry about ", after:" sometimes.",
        opts:[["money","돈"],["my health","건강"],["work","일"],["the future","앞날"]] },
  25: { before:"It takes me a while to ", after:".",
        opts:[["get started","시작하다"],["wake up","잠에서 깨다"],["make up my mind","마음을 정하다"]] },
  28: { before:"I just want ", after:".",
        opts:[["a stable life","안정적인 삶"],["a quiet life","조용한 삶"],["more free time","여유 시간"],["a good sleep","푹 자는 것"]] }
};

/* 추가 표현 — 오늘 문장의 틀에 단어만 갈아끼운 문장들.
   [영어, 뜻, 한글발음] 세 개가 기본이고, 네 번째 칸은 「? 설명」입니다.
   오늘 문장에 없던 모양이 나올 때만 네 번째 칸을 답니다. 없으면 ? 버튼도 안 생깁니다.
   열쇠는 DAY 번호. 없는 날은 칸 자체가 안 보입니다. 기존 30문장은 건드리지 않습니다 */
const EXTRA = {
1: [["I'm learning Korean.","한국어를 배우고 있어요.","아임 러닝 코리안"],
    ["I'm learning to cook.","요리를 배우고 있어요.","아임 러닝 투 쿡",
     "배우는 게 말·과목이면 그냥 붙여요 (English, Korean). 배우는 게 「하는 일」이면 앞에 to 를 넣어요. to cook = 요리하기, to drive = 운전하기."],
    ["I'm learning something new every day.","매일 새로운 걸 배우고 있어요.","아임 러닝 썸띵 뉴 에브리 데이",
     "something 은 「뭔가 하나」예요. 꾸미는 말을 뒤에 붙여서 something new = 새로운 뭔가 가 돼요."]],

2: [["I'm a total beginner.","저 완전 초보예요.","아임 어 토털 비기너",
     "complete 자리에 total 을 넣어도 뜻이 거의 같아요. 둘 다 「완전」이에요."],
    ["I'm a complete beginner at cooking.","요리는 완전 초보예요.","아임 어 컴플릿 비기너 앳 쿠킹",
     "뒤에 at 을 붙이면 「무엇에」 초보인지 말할 수 있어요. at 다음에 오는 동작은 -ing 을 붙여요. cook → cooking."],
    ["I'm a beginner at this.","이건 제가 초보예요.","아임 어 비기너 앳 디스",
     "complete 를 빼면 「완전」이 빠지고 그냥 초보가 돼요. this = 지금 이것."]],

3: [["I'm taking it easy.","무리 안 하고 있어요.","아임 테이킹 잇 이지",
     "slow 를 easy 로 바꾸면 「힘 빼고 편하게」가 돼요. 쉬엄쉬엄한다는 느낌이에요."],
    ["We're taking it slow.","우리는 천천히 하고 있어요.","위어 테이킹 잇 슬로우",
     "나 혼자면 I'm, 둘 이상이면 We're 로 바꿔요."],
    ["I'm taking it one day at a time.","하루하루 해나가고 있어요.","아임 테이킹 잇 원 데이 앳 어 타임",
     "one day at a time = 한 번에 하루씩. 멀리 안 보고 오늘만 본다는 말이에요."]],

4: [["I like learning new words.","새 단어 배우는 걸 좋아해요.","아이 라익 러닝 뉴 워즈"],
    ["I like meeting new people.","새로운 사람 만나는 걸 좋아해요.","아이 라익 미팅 뉴 피플",
     "like 뒤에 오는 동작은 -ing 을 붙여요. meet → meeting, try → trying."],
    ["I like trying new food.","새로운 음식 먹어보는 걸 좋아해요.","아이 라익 트라잉 뉴 푸드",
     "try 는 「한번 해보다」예요. 음식에 쓰면 「먹어보다」가 돼요."]],

5: [["I try to read a little every day.","매일 조금씩 읽으려고 해요.","아이 트라이 투 리드 어 리틀 에브리 데이"],
    ["I try to walk every day.","매일 걸으려고 해요.","아이 트라이 투 웍 에브리 데이",
     "a little(조금) 은 빼도 돼요. 빼면 「매일 걷는다」만 남아요."],
    ["I try to study a little every night.","매일 밤 조금씩 공부하려고 해요.","아이 트라이 투 스터디 어 리틀 에브리 나잇",
     "every day 자리에 every night(매일 밤), every week(매주) 도 넣을 수 있어요."]],

6: [["I don't always have time.","항상 시간이 있는 건 아니에요.","아이 돈트 올웨이즈 해브 타임",
     "don't always 는 「전혀 아니다」가 아니라 「항상 그런 건 아니다」예요. 가끔은 그렇다는 말이에요."],
    ["I don't always feel like going out.","항상 나가고 싶은 건 아니에요.","아이 돈트 올웨이즈 필 라익 고잉 아웃",
     "feel like 뒤에 하고 싶은 일을 넣을 때는 -ing 을 붙여요. go out → going out."],
    ["I don't always feel like talking.","항상 말하고 싶은 건 아니에요.","아이 돈트 올웨이즈 필 라익 토킹"]],

7: [["But I still do it.","그래도 해요.","벗 아이 스틸 두 잇",
     "try(해보다) 자리에 do it(그걸 한다) 을 넣은 거예요."],
    ["But I still go.","그래도 가요.","벗 아이 스틸 고우"],
    ["I still want to try.","그래도 해보고 싶어요.","아이 스틸 원트 투 트라이",
     "want to + 동작 = 「~하고 싶다」. 앞의 But 은 빼도 말이 돼요."]],

8: [["I'm learning to drive.","운전을 배우고 있어요.","아임 러닝 투 드라이브"],
    ["I'm learning to swim.","수영을 배우고 있어요.","아임 러닝 투 스윔"],
    ["I'm learning to make videos.","영상 만드는 걸 배우고 있어요.","아임 러닝 투 메이크 비디오즈",
     "to 뒤에는 동작 하나만 오는 게 아니라 「make videos(영상을 만들다)」처럼 이어 붙일 수도 있어요."]],

9: [["I'm working on a new project.","새 프로젝트를 하고 있어요.","아임 워킹 온 어 뉴 프로젝트"],
    ["I'm working on my English.","영어를 붙잡고 있어요.","아임 워킹 온 마이 잉글리시",
     "work on 뒤에 공부나 실력을 넣으면 「그걸 늘리려고 애쓰는 중」이라는 뜻이 돼요."],
    ["I'm working on something small.","작은 걸 하나 하고 있어요.","아임 워킹 온 썸띵 스몰",
     "something 은 꾸미는 말을 뒤에 붙여요. something small = 작은 뭔가."]],

10: [["I use my computer almost every day.","컴퓨터를 거의 매일 써요.","아이 유즈 마이 컴퓨터 올모스트 에브리 데이"],
     ["I use it every day.","그거 매일 써요.","아이 유즈 잇 에브리 데이",
      "almost 를 빼면 「거의」가 빠지고 진짜 매일이 돼요."],
     ["I use this app almost every morning.","이 앱을 거의 매일 아침 써요.","아이 유즈 디스 앱 올모스트 에브리 모닝"]],

11: [["I worked on it again yesterday.","어제도 그거 했어요.","아이 웍트 온 잇 어게인 예스터데이",
      "today(오늘) 자리에 yesterday(어제) 를 넣었어요. 이미 한 일이라 worked 는 그대로예요."],
     ["I worked on my project today.","오늘 제 프로젝트를 했어요.","아이 웍트 온 마이 프로젝트 투데이",
      "it(그거) 자리에 무엇을 했는지 그대로 넣을 수 있어요."],
     ["I practiced English again today.","오늘 또 영어 연습했어요.","아이 프랙티스트 잉글리시 어게인 투데이",
      "동작 뒤에 -ed 를 붙이면 「이미 한 일」이 돼요. practice → practiced, work → worked."]],

12: [["I got a lot done.","많이 해냈어요.","아이 갓 어 랏 던",
      "a little(조금) 자리에 a lot(많이) 을 넣으면 반대말이 돼요."],
     ["I got nothing done.","아무것도 못 했어요.","아이 갓 낫띵 던",
      "nothing 은 「아무것도 없음」이에요. 그래서 하나도 못 했다는 말이 돼요."],
     ["I got a little done today.","오늘 조금 해냈어요.","아이 갓 어 리틀 던 투데이"]],

13: [["I'm still learning.","아직 배우는 중이에요.","아임 스틸 러닝"],
     ["We're still figuring it out.","우리도 아직 알아가는 중이에요.","위어 스틸 피겨링 잇 아웃",
      "나 혼자면 I'm, 둘 이상이면 We're 예요."],
     ["I'm still getting used to it.","아직 익숙해지는 중이에요.","아임 스틸 게팅 유즈드 투 잇",
      "get used to ~ 는 「~에 익숙해지다」예요. 여기서 it 은 「그거」."]],

14: [["I learn a lot from other people.","다른 사람들한테서 많이 배워요.","아이 런 어 랏 프롬 아더 피플",
      "from 은 「~한테서, ~에서」예요. 어디서 배웠는지를 넣는 자리예요. a lot 은 「많이」."],
     ["We learn from our mistakes.","우리는 실수하면서 배워요.","위 런 프롬 아워 미스테익스",
      "나는 my, 우리는 our 로 바꿔요."],
     ["I learned a lot from it.","그걸로 많이 배웠어요.","아이 런드 어 랏 프롬 잇",
      "learn 에 -ed 를 붙이면 이미 배운 일이 돼요."]],

15: [["I like making videos.","영상 만드는 걸 좋아해요.","아이 라익 메이킹 비디오즈"],
     ["I like making small things.","작은 거 만드는 걸 좋아해요.","아이 라익 메이킹 스몰 띵스"],
     ["I like drawing.","그림 그리는 걸 좋아해요.","아이 라익 드로잉",
      "like 뒤에 오는 동작은 -ing 을 붙여요. draw → drawing."]],

16: [["I like having a plan.","계획이 있는 걸 좋아해요.","아이 라익 해빙 어 플랜"],
     ["I like having a quiet morning.","조용한 아침을 좋아해요.","아이 라익 해빙 어 콰이엇 모닝"],
     ["I like keeping things simple.","단순하게 두는 걸 좋아해요.","아이 라익 키핑 띵스 심플",
      "keep ~ simple 은 「~을 단순한 채로 둔다」예요. have 자리에 keep 을 넣은 거예요."]],

17: [["I spend a lot of time alone.","혼자 있는 시간이 많아요.","아이 스펜드 어 랏 오브 타임 얼론"],
     ["I spend a lot of time on my phone.","휴대폰 보는 시간이 많아요.","아이 스펜드 어 랏 오브 타임 온 마이 폰",
      "on my phone 은 「휴대폰 위에」가 아니라 「휴대폰으로 뭔가 하는 중」이에요."],
     ["I don't spend much time outside.","밖에서 보내는 시간은 많지 않아요.","아이 돈트 스펜드 머치 타임 아웃사이드",
      "아니라고 할 때는 a lot of 대신 don't ~ much 를 써요."]],

18: [["I read books in my free time.","시간 날 때 책 읽어요.","아이 리드 북스 인 마이 프리 타임"],
     ["I watch videos in my free time.","시간 날 때 영상 봐요.","아이 워치 비디오즈 인 마이 프리 타임"],
     ["I knit in my free time.","시간 날 때 뜨개질해요.","아이 닛 인 마이 프리 타임",
      "knit 의 k 는 소리를 안 내요. 「크닛」이 아니라 「닛」이에요."]],

19: [["I also like cooking.","요리도 좋아해요.","아이 올소 라익 쿠킹"],
     ["I also like walking.","걷는 것도 좋아해요.","아이 올소 라익 워킹"],
     ["I also like quiet places.","조용한 곳도 좋아해요.","아이 올소 라익 콰이엇 플레이시즈",
      "like 뒤에 동작이 아니라 「것·곳」이 오면 -ing 을 안 붙여요."]],

20: [["I like having time to think.","생각할 시간이 있는 걸 좋아해요.","아이 라익 해빙 타임 투 띵크",
      "time to ~ 는 「~할 시간」이에요. to 뒤에 하고 싶은 일을 넣어요."],
     ["I need time to myself.","혼자만의 시간이 필요해요.","아이 니드 타임 투 마이셀프",
      "like(좋아해요) 자리에 need(필요해요) 를 넣으면 더 센 말이 돼요."],
     ["I don't have much time to myself.","혼자만의 시간이 많지 않아요.","아이 돈트 해브 머치 타임 투 마이셀프"]],

21: [["I get nervous about money sometimes.","가끔 돈 생각하면 불안해져요.","아이 겟 너버스 어바웃 머니 썸타임즈"],
     ["I get nervous before a test.","시험 전에 긴장돼요.","아이 겟 너버스 비포 어 테스트",
      "about(~에 대해) 대신 before(~전에) 를 쓰면 「언제」를 말하게 돼요."],
     ["I don't get nervous about it anymore.","이제 그건 긴장 안 돼요.","아이 돈트 겟 너버스 어바웃 잇 애니모어",
      "not ~ anymore 는 「이제는 아니다」예요."]],

22: [["I worry about my health sometimes.","가끔 건강 걱정을 해요.","아이 워리 어바웃 마이 헬스 썸타임즈"],
     ["I worry about work sometimes.","가끔 일 걱정을 해요.","아이 워리 어바웃 웍 썸타임즈"],
     ["Don't worry about it.","그건 걱정 마세요.","돈트 워리 어바웃 잇",
      "앞에 Don't 를 붙이면 상대에게 「하지 마세요」라고 하는 말이 돼요."]],

23: [["I get tired sometimes.","가끔 지쳐요.","아이 겟 타이어드 썸타임즈",
      "overwhelmed(벅찬) 자리에 다른 기분을 넣을 수 있어요. tired = 지친."],
     ["I get overwhelmed at work.","일할 때 벅차요.","아이 겟 오버웰름드 앳 웍",
      "sometimes(가끔) 자리에 「언제」를 넣은 거예요. at work = 일하는 자리에서."],
     ["I don't get overwhelmed easily.","저는 쉽게 벅차하지 않아요.","아이 돈트 겟 오버웰름드 이즐리"]],

24: [["I take things slowly.","천천히 해요.","아이 테익 띵스 슬로울리",
      "slow 에 -ly 를 붙이면 「천천히」라는 말이 돼요."],
     ["We take things one step at a time.","우리는 하나씩 해요.","위 테익 띵스 원 스텝 앳 어 타임"],
     ["I do one thing at a time.","한 번에 하나씩 해요.","아이 두 원 띵 앳 어 타임",
      "one step at a time(한 걸음씩) 을 one thing at a time(한 가지씩) 으로 바꾼 거예요."]],

25: [["It takes me a while to wake up.","저는 잠 깨는 데 시간이 좀 걸려요.","잇 테익스 미 어 와일 투 웨이크 업"],
     ["It takes me a while to decide.","저는 정하는 데 시간이 좀 걸려요.","잇 테익스 미 어 와일 투 디사이드"],
     ["It doesn't take long.","오래 안 걸려요.","잇 더즌트 테익 롱",
      "아니라고 할 때는 doesn't 를 써요. a while(좀 오래) 대신 long(오래) 을 씁니다."]],

26: [["Once I start, I don't stop.","한번 시작하면 안 멈춰요.","원스 아이 스타트, 아이 돈트 스탑",
      "앞의 But 은 빼도 돼요. 빼면 앞 문장과 이어지는 느낌만 없어져요."],
     ["Once I start, I can keep going.","한번 시작하면 계속할 수 있어요.","원스 아이 스타트, 아이 캔 킵 고잉",
      "keep + -ing 는 「계속 ~하다」예요. keep going = 계속 가다."],
     ["I can focus pretty well in the morning.","아침에는 꽤 집중이 잘 돼요.","아이 캔 포커스 프리티 웰 인 더 모닝"]],

27: [["I'm trying to be more patient.","좀 더 참을성 있으려고 하고 있어요.","아임 트라잉 투 비 모어 페이션트"],
     ["I'm trying to sleep more.","잠을 더 자려고 하고 있어요.","아임 트라잉 투 슬립 모어",
      "be(~인 상태가 되다) 는 「어떤 사람이 되는」 말에 써요. 그냥 동작이면 be 를 빼고 바로 써요."],
     ["I'm trying to eat better.","더 잘 먹으려고 하고 있어요.","아임 트라잉 투 잇 베터",
      "well(잘) 의 「더」는 weller 가 아니라 better 예요."]],

28: [["I just want a quiet life.","그냥 조용한 삶을 원해요.","아이 저스트 원트 어 콰이엇 라이프"],
     ["I just want more time.","그냥 시간이 더 있었으면 해요.","아이 저스트 원트 모어 타임"],
     ["I just want to rest.","그냥 쉬고 싶어요.","아이 저스트 원트 투 레스트",
      "want 뒤에 「하고 싶은 일」이 오면 앞에 to 를 붙여요. to rest = 쉬기."]],

29: [["I want to keep going.","계속 가고 싶어요.","아이 원트 투 킵 고잉"],
     ["I want to keep trying.","계속 해보고 싶어요.","아이 원트 투 킵 트라잉",
      "keep 뒤에 오는 동작은 -ing 을 붙여요. try → trying."],
     ["I want to learn more.","더 배우고 싶어요.","아이 원트 투 런 모어",
      "keep(계속) 을 빼고 바로 동작을 쓸 수도 있어요."]],

30: [["I'm glad I started.","시작한 게 기뻐요.","아임 글래드 아이 스타티드"],
     ["I'm glad I tried.","해본 게 기뻐요.","아임 글래드 아이 트라이드",
      "tried 는 try(해보다) 의 「이미 한 일」 모양이에요."],
     ["I'm glad you came.","와줘서 기뻐요.","아임 글래드 유 케임",
      "I 자리에 you 를 넣으면 「당신이 ~한 것」이 기쁘다는 말이 돼요."]]
};

/* 복습 사다리 — 처음 배운 날을 0일로 */
const LADDER = [1, 3, 7, 14, 30];
